name = "ai-proxy-money"
main = "index.js"
compatibility_date = "2024-10-13"

# Enable comprehensive logging for debugging
[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1.0
invocation_logs = true
persist = true

# Environment variables (non-secret config)
[vars]
# Add any non-sensitive configuration variables here
# Example:
# API_BASE_URL = "https://api.openai.com"
# DEFAULT_MODEL = "gpt-3.5-turbo"

# ESModule rules for JavaScript files
[[rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = true
